[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "7_inch_MAVLink_Mission"
version = "0.1.0"
description = "MAVLink mission for a 7-inch quad."
readme = "README.md"

requires-python = ">=3.13"
dependencies = [
    "pymavlink"
]